name: Deploy Static Website

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

# 환경 변수를 추가하여 Node.js 24를 미리 강제로 사용합니다 (경고 제거용)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5 # 최신 버전으로 업데이트

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
