name: Deploy Static Website

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

# 2026년 기준, 강제 실행 옵션 없이도 자연스럽게 작동하도록 설정
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v4는 내부적으로 업데이트를 지원함

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        # v4로 버전을 올리면 Node.js 24 환경에 최적화됩니다.
        uses: actions/upload-pages-artifact@v3 
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
